### ISSUE TITLE
Add button to change langage

### ISSUE THREAD

**Issue by Stefal** [panoramax-project/panoramax-website#30]
Right now, the panoramax website langage is detected automatically. There is no way to change it manually.

Automatic detection, is cool, but please add a button to change the langage.

**Comment by natrius** [comment]
Today there is a button :D Its still a bit broken, but its there 
![image](https://github.com/panoramax-project/panoramax-website/assets/7243447/a6c34fdc-085d-47f2-9f00-6f19d8138677)

**Comment by mnalis** [comment]
Seems to work for me, can you close this issue @Stefal if it now works for you?
