### ISSUE TITLE
FR: Ajout logo Carto'Cité

### ISSUE THREAD

**Issue by Stefal** [panoramax-project/panoramax-website#6]
Hello !

Pour faire suite à la réunion de tout à l'heure, voici le logo de Carto'Cité pour l'ajouter à la page web panoramax.fr
![Logo CartoCite or](https://user-images.githubusercontent.com/8255984/211386794-0a741f5e-51a9-4575-812e-3c6b020b4d34.png)

Au besoin, on a une version svg.

Désolé, pas de Pull Request pour cette fois, je ne connais pas du tout Vue.

**Comment by J2A2B** [comment]
C'est fait merci :)
