### ISSUE TITLE
Lien IGN incorrect

### ISSUE THREAD

**Issue by Jean-BaptisteC** [panoramax-project/panoramax-website#8]
Ce lien IGN retourne une erreur 404 https://github.com/panoramax-project/panoramax-website/blob/e5059be0cc97267853fe3e7f461bbf83673fa05d/src/locales/fr.json#L132 

Est ce que le bon lien serait celui-ci https://www.ign.fr/institut/la-fabrique-des-geocommuns-incubateur-de-communs-lign ?

**Comment by J2A2B** [comment]
C'est modifié merci
